add_executable(test_reader test_reader.cpp)
target_link_libraries(test_reader PRIVATE CUE4Parse)
add_test(NAME test_reader COMMAND test_reader)

add_executable(test_more_readers test_more_readers.cpp)
target_link_libraries(test_more_readers PRIVATE CUE4Parse)
add_test(NAME test_more_readers COMMAND test_more_readers)

add_executable(test_compression_utils test_compression_utils.cpp)
target_link_libraries(test_compression_utils PRIVATE CUE4Parse)
add_test(NAME test_compression_utils COMMAND test_compression_utils)

add_executable(test_core_misc test_core_misc.cpp)
target_link_libraries(test_core_misc PRIVATE CUE4Parse)
add_test(NAME test_core_misc COMMAND test_core_misc)

add_executable(test_package_summary test_package_summary.cpp)
target_link_libraries(test_package_summary PRIVATE CUE4Parse)
add_test(NAME test_package_summary COMMAND test_package_summary)

add_executable(test_compressed_proxy test_compressed_proxy.cpp)
target_link_libraries(test_compressed_proxy PRIVATE CUE4Parse)
add_test(NAME test_compressed_proxy COMMAND test_compressed_proxy)

add_executable(test_name_pool test_name_pool.cpp)
target_link_libraries(test_name_pool PRIVATE CUE4Parse)
add_test(NAME test_name_pool COMMAND test_name_pool)

add_executable(test_object_resource test_object_resource.cpp)
target_link_libraries(test_object_resource PRIVATE CUE4Parse)
add_test(NAME test_object_resource COMMAND test_object_resource)

add_executable(test_package test_package.cpp)
target_link_libraries(test_package PRIVATE CUE4Parse)
add_test(NAME test_package COMMAND test_package)

add_executable(test_properties test_properties.cpp)
target_link_libraries(test_properties PRIVATE CUE4Parse)
add_test(NAME test_properties COMMAND test_properties)

add_executable(test_aggregate_properties test_aggregate_properties.cpp)
target_link_libraries(test_aggregate_properties PRIVATE CUE4Parse)
add_test(NAME test_aggregate_properties COMMAND test_aggregate_properties)

add_executable(test_container_properties test_container_properties.cpp)
target_link_libraries(test_container_properties PRIVATE CUE4Parse)
add_test(NAME test_container_properties COMMAND test_container_properties)

add_executable(test_soft_object_properties test_soft_object_properties.cpp)
target_link_libraries(test_soft_object_properties PRIVATE CUE4Parse)
add_test(NAME test_soft_object_properties COMMAND test_soft_object_properties)

add_executable(test_delegate_properties test_delegate_properties.cpp)
target_link_libraries(test_delegate_properties PRIVATE CUE4Parse)
add_test(NAME test_delegate_properties COMMAND test_delegate_properties)

add_executable(test_text_properties test_text_properties.cpp)
target_link_libraries(test_text_properties PRIVATE CUE4Parse)
add_test(NAME test_text_properties COMMAND test_text_properties)

add_executable(test_package_loading test_package_loading.cpp)
target_link_libraries(test_package_loading PRIVATE CUE4Parse)
add_test(NAME test_package_loading COMMAND test_package_loading)

add_executable(test_file_provider test_file_provider.cpp)
target_link_libraries(test_file_provider PRIVATE CUE4Parse)
add_test(NAME test_file_provider COMMAND test_file_provider)

add_executable(test_string_table test_string_table.cpp)
target_link_libraries(test_string_table PRIVATE CUE4Parse)
add_test(NAME test_string_table COMMAND test_string_table)

add_executable(test_datatable test_datatable.cpp)
target_link_libraries(test_datatable PRIVATE CUE4Parse)
add_test(NAME test_datatable COMMAND test_datatable)

add_executable(test_type_system test_type_system.cpp)
target_link_libraries(test_type_system PRIVATE CUE4Parse)
add_test(NAME test_type_system COMMAND test_type_system)

add_executable(test_redirector_bpgc test_redirector_bpgc.cpp)
target_link_libraries(test_redirector_bpgc PRIVATE CUE4Parse)
add_test(NAME test_redirector_bpgc COMMAND test_redirector_bpgc)

add_executable(test_soft_object_load test_soft_object_load.cpp)
target_link_libraries(test_soft_object_load PRIVATE CUE4Parse)
add_test(NAME test_soft_object_load COMMAND test_soft_object_load)

add_executable(test_userdefined test_userdefined.cpp)
target_link_libraries(test_userdefined PRIVATE CUE4Parse)
add_test(NAME test_userdefined COMMAND test_userdefined)

add_executable(test_curvetable test_curvetable.cpp)
target_link_libraries(test_curvetable PRIVATE CUE4Parse)
add_test(NAME test_curvetable COMMAND test_curvetable)

add_executable(test_curveassets test_curveassets.cpp)
target_link_libraries(test_curveassets PRIVATE CUE4Parse)
add_test(NAME test_curveassets COMMAND test_curveassets)

add_executable(test_linearcolor test_linearcolor.cpp)
target_link_libraries(test_linearcolor PRIVATE CUE4Parse)
add_test(NAME test_linearcolor COMMAND test_linearcolor)

add_executable(test_vectors test_vectors.cpp)
target_link_libraries(test_vectors PRIVATE CUE4Parse)
add_test(NAME test_vectors COMMAND test_vectors)

add_executable(test_compression_codecs test_compression_codecs.cpp)
target_link_libraries(test_compression_codecs PRIVATE CUE4Parse)
add_test(NAME test_compression_codecs COMMAND test_compression_codecs)

add_executable(test_geometry test_geometry.cpp)
target_link_libraries(test_geometry PRIVATE CUE4Parse)
add_test(NAME test_geometry COMMAND test_geometry)

add_executable(test_bounds test_bounds.cpp)
target_link_libraries(test_bounds PRIVATE CUE4Parse)
add_test(NAME test_bounds COMMAND test_bounds)

add_executable(test_aes test_aes.cpp)
target_link_libraries(test_aes PRIVATE CUE4Parse)
add_test(NAME test_aes COMMAND test_aes)

add_executable(test_memory_image test_memory_image.cpp)
target_link_libraries(test_memory_image PRIVATE CUE4Parse)
add_test(NAME test_memory_image COMMAND test_memory_image)

add_executable(test_pak test_pak.cpp)
target_link_libraries(test_pak PRIVATE CUE4Parse)
add_test(NAME test_pak COMMAND test_pak)

add_executable(test_default_file_provider test_default_file_provider.cpp)
target_link_libraries(test_default_file_provider PRIVATE CUE4Parse)
add_test(NAME test_default_file_provider COMMAND test_default_file_provider)

add_executable(test_io_store test_io_store.cpp)
target_link_libraries(test_io_store PRIVATE CUE4Parse)
add_test(NAME test_io_store COMMAND test_io_store)

add_executable(test_zen_package test_zen_package.cpp)
target_link_libraries(test_zen_package PRIVATE CUE4Parse)
add_test(NAME test_zen_package COMMAND test_zen_package)

add_executable(test_script_struct test_script_struct.cpp)
target_link_libraries(test_script_struct PRIVATE CUE4Parse)
add_test(NAME test_script_struct COMMAND test_script_struct)

add_executable(test_config_ini test_config_ini.cpp)
target_link_libraries(test_config_ini PRIVATE CUE4Parse)
add_test(NAME test_config_ini COMMAND test_config_ini)

add_executable(test_version_container test_version_container.cpp)
target_link_libraries(test_version_container PRIVATE CUE4Parse)
add_test(NAME test_version_container COMMAND test_version_container)

add_executable(test_custom_versions test_custom_versions.cpp)
target_link_libraries(test_custom_versions PRIVATE CUE4Parse)
add_test(NAME test_custom_versions COMMAND test_custom_versions)

add_executable(test_wwise_fmod_enums test_wwise_fmod_enums.cpp)
target_link_libraries(test_wwise_fmod_enums PRIVATE CUE4Parse)
add_test(NAME test_wwise_fmod_enums COMMAND test_wwise_fmod_enums)

add_executable(test_bulk_enums test_bulk_enums.cpp)
target_link_libraries(test_bulk_enums PRIVATE CUE4Parse)
add_test(NAME test_bulk_enums COMMAND test_bulk_enums)

add_executable(test_wwise test_wwise.cpp)
target_link_libraries(test_wwise PRIVATE CUE4Parse)
add_test(NAME test_wwise COMMAND test_wwise)

add_executable(test_bulkdata_wwisereader test_bulkdata_wwisereader.cpp)
target_link_libraries(test_bulkdata_wwisereader PRIVATE CUE4Parse)
add_test(NAME test_bulkdata_wwisereader COMMAND test_bulkdata_wwisereader)

add_executable(test_sound_metasound test_sound_metasound.cpp)
target_link_libraries(test_sound_metasound PRIVATE CUE4Parse)
add_test(NAME test_sound_metasound COMMAND test_sound_metasound)

add_executable(test_fmod_bank test_fmod_bank.cpp)
target_link_libraries(test_fmod_bank PRIVATE CUE4Parse)
add_test(NAME test_fmod_bank COMMAND test_fmod_bank)

add_executable(test_object_type_registry test_object_type_registry.cpp)
target_link_libraries(test_object_type_registry PRIVATE CUE4Parse)
add_test(NAME test_object_type_registry COMMAND test_object_type_registry)

add_executable(test_audio_providers test_audio_providers.cpp)
target_link_libraries(test_audio_providers PRIVATE CUE4Parse)
add_test(NAME test_audio_providers COMMAND test_audio_providers)

add_executable(test_texture test_texture.cpp)
target_link_libraries(test_texture PRIVATE CUE4Parse)
add_test(NAME test_texture COMMAND test_texture)

add_executable(test_zstd test_zstd.cpp)
target_link_libraries(test_zstd PRIVATE CUE4Parse)
add_test(NAME test_zstd COMMAND test_zstd)

add_executable(test_brotli test_brotli.cpp)
target_link_libraries(test_brotli PRIVATE CUE4Parse)
add_test(NAME test_brotli COMMAND test_brotli)
